language: node_js
node_js:
  - "node"
script:
  - npm run build
  - npm run test
  - npm run docs
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  skip-cleanup: true
  local-dir: docs/html/chrysalis-focus/0.0.1
  on:
    branch: master
